Repository alephium/awesome-alephium, pull requests merged in 2021-11, with the labels that each got.

#4 Update: add link to systemd services (sven-hash)
  README.md
Labels: ALPH-50

#6 Add telegram bot
  README.md
Labels: ALPH-500

#7 Update README.md
  README.md
Labels: ALPH-100
