Repository alephium/awesome-alephium, pull requests merged in 2021-12, with the labels that each got.

#8 Adding PowerShell version of diomark's script.
  README.md
Labels: ALPH-50

#9 Update README.md
  README.md
Labels: ALPH-100

#10 Telegram whales watcher channel
  README.md
Labels: ALPH-300

#11 Add contributors profile picture
  README.md
Labels: ALPH-50

#14 Reunite spreadsheet and form
  README.md
Labels: ALPH-50

#16 added walkthrough on mining using vast.ai
  README.md
Labels: ALPH-50

#15 Claim your address
  README.md
Labels: ALPH-50

#18 Adding a powershell version of sweep all
  README.md
Labels: ALPH-25
